name: posts_app
description: A flutter app to learn dependency injection with clean code.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  auto_route: ^5.0.4
  dio: ^5.0.1
  dartz: ^0.10.1
  another_flushbar: ^1.12.29
  salem_package:
    git: https://github.com/SalemZakkar/SalemPackage.git
dev_dependencies:
    flutter_test:
      sdk: flutter
    build_runner: ^2.3.3
    injectable_generator:
    flutter_lints: ^2.0.0
    auto_route_generator: ^5.0.3
    flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21




flutter:
  uses-material-design: true

